Mysite/Mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mysite/accounts/urls.py
from django.urls import path
from .views import SignUP

urlpatterns = [
    path('signup/', SignUP.as_view(), name='signup')
]

Mysite/films/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FilmsView.as_view(), name='home'),
    path('<slug:slug>/', views.FilmDetail.as_view(), name='film_detail'),
    path('reviews/<int:pk>/', views.AddReview.as_view(), name='add_review')
]

Mysite/accounts/models.py
from django.db import models

# Create your models here.

Mysite/films/models.py
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    '''Жанры фильмов'''
    name = models.CharField('Название жанра', max_length=50)
    description = models.TextField('Описание', blank=True)
    url = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Direction(models.Model):
    '''Режисcеры'''
    name = models.CharField('Фамилия и имя', max_length=150)
    description = models.TextField('Биография', blank=True)
    image = models.ImageField('Фотография', upload_to='image/directions/%Y')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Режиcсер'
        verbose_name_plural = 'Режисcеры'


class Film(models.Model):
    '''Информация о фильме'''
    title = models.CharField('Название фильма', max_length=100)
    image = models.ImageField('Постер', upload_to='image/%Y')
    description = models.TextField(blank=True)
    date_publ = models.DateField('Дата выхода')
    directions = models.ManyToManyField(Direction, verbose_name='Режиcсеры')
    genre = models.ManyToManyField(Genre, verbose_name='Жанры')
    url = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.title}, {self.date_publ}'

    def get_absolute_url(self):
        return reverse('film_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'

class Reviews(models.Model):
    '''Отзывы'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_reviews = models.TextField('Текст отзыва', max_length=3000)
    film = models.ForeignKey(Film, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.film}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

Mysite/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUP(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

Mysite/films/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Film
from .form import ReviewForm

class FilmsView(View):
    '''Список фильмов'''
    def get(self, request):
        films = Film.objects.all()
        return render(request, 'films/film.html', {'film_list': films})

class FilmDetail(View):
    '''Представление одного фильма'''
    def get(self, request, slug):
        film = Film.objects.get(url=slug)
        return render(request, 'films/film_detail.html', {'film': film})


class AddReview(View):
    '''добавление отзыва'''
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        film = Film.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.film = film
            form.save()
        return redirect(film.get_absolute_url())

Mysite/templates/films/film.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <!-- Page Title -->
    <title>Мой портал</title>

    <!-- Meta Data -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Уроки по Adobe Photoshop">


    <!-- Web Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli%7CRubik:400,400i,500,700">

    <!-- ======= Bootstrap CSS ======= -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- ======= Main Stylesheet ======= -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">


</head>

<body>

    <!-- Header Begin -->
    <header class="header">
        <!-- Header Style One Begin -->
        <div class="header-main style--one">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-sm-4 col-8">
                        <!-- Logo Begin -->
                        <div class="logo">
                            <a href="index.html">
                                <img class="default-logo" src="{% static '/img/logo.png' %}" data-rjs="2" alt="">
                            </a>
                        </div>
                        <!-- Logo End -->
                    </div>

                    <div class="col-lg-9 col-sm-8 col-4">
                        <!-- Main Menu Begin -->
                        <div class="main-menu d-flex align-items-center justify-content-end">
                            <ul class="nav align-items-center">
                                <li class="current-menu-parent menu-item-has-children" >
                                    <a href="/">Главная</a>
                                </li>
                                <li class="menu-item-has-children">
                                    {% if user.is_authenticated %}
                                    <p>Привет, {{ user.username }}, вы авторизованы на сайте!</p>
                                    <a href="{% url 'logout' %}">Выход</a></li>
                                    {% else %}
                                    <li class="menu-item-has-children"><a href="{% url 'signup' %}">Регистрация</a></li>
                                    <li class="menu-item-has-children"><a href="{% url 'login' %}">Авторизация</a></li>
                                    {% endif %}


                            </ul>

                        </div>
                        <!-- Main Menu ENd -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Header Style One End -->
    </header>
    <!-- Header End -->

    <!-- Project Begin -->
    <section class="section-pattern">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Section Title Begin -->
                    <div class="section-title text-center">
                        <h3>Записи</h3>
                        <h2>Фильмы</h2>

                    </div>
                    <!-- Section Title End -->
                </div>
            </div>

            <div class="row project-items grid">
                {% for film in film_list %}
                <!-- Single Project Begin -->
                <div class="col-lg-6 grid-item sales business">
                    <div class="single-project-item">
                        <!-- Project Image Begin -->
                        <div class="image">
                            <img src="{{ film.image.url }}" data-rjs="2" alt="">
                        </div>
                        <!-- Project Image End -->

                        <!-- Project Body Begin -->
                        <div class="project-body">
                            <h3>{{ film.title }}</h3>
                            <p>{{ film.description }}</p>
                            <a href="/{{ film.url }}/" class="btn-inline" target="_blank">Перейти</a>
                        </div>
                        <!-- Project Body End -->
                    </div>
                </div>
                <!-- Single Project End -->
                {% endfor %}

            </div>

        </div>
    </section>
    <!-- Project End -->


    <!-- Footer Begin -->
    <footer class="footer bg-light section-pattern footer-bg" data-bg-img="assets/img/section-pattern/footer-pattern.png">
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="copyright-text text-center">
                            <span>&copy; Copyright 2022.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

    </footer>
    <!-- Footer End -->


</body>
</html>

Mysite/templates/films/film_detail.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
<head>
    <!-- Page Title -->
    <title>Мой портал</title>

    <!-- Meta Data -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Уроки по Adobe Photoshop">


    <!-- Web Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli%7CRubik:400,400i,500,700">

    <!-- ======= Bootstrap CSS ======= -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- ======= Main Stylesheet ======= -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">


</head>

<body>

    <!-- Header Begin -->
    <header class="header">
        <!-- Header Style One Begin -->
        <div class="header-main style--one">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-sm-4 col-8">
                        <!-- Logo Begin -->
                        <div class="logo">
                            <a href="index.html">
                                <img class="default-logo" src="{% static '/img/logo.png' %}" data-rjs="2" alt="">
                            </a>
                        </div>
                        <!-- Logo End -->
                    </div>

                    <div class="col-lg-9 col-sm-8 col-4">
                        <!-- Main Menu Begin -->
                        <div class="main-menu d-flex align-items-center justify-content-end">
                            <ul class="nav align-items-center">
                                <li class="current-menu-parent menu-item-has-children" >
                                    <a href="/">Главная</a>
                                </li>
                                <li class="menu-item-has-children">
                                    {% if user.is_authenticated %}
                                    <p>Привет, {{ user.username }}, вы авторизованы на сайте!</p>
                                    <a href="{% url 'logout' %}">Выход</a></li>
                                    {% else %}
                                    <li class="menu-item-has-children"><a href="{% url 'signup' %}">Регистрация</a></li>
                                    <li class="menu-item-has-children"><a href="{% url 'login' %}">Авторизация</a></li>
                                    {% endif %}

                            </ul>

                        </div>
                        <!-- Main Menu ENd -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Header Style One End -->
    </header>
    <!-- Header End -->

    <!-- Project Begin -->
    <section class="section-pattern">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Section Title Begin -->
                    <div class="section-title text-center">
                        <h3>Записи</h3>
                        <h2>{{ film.title }}</h2>

                    </div>
                    <!-- Section Title End -->
                </div>
            </div>

            <div class="row project-items grid">
                <div class="project-body">
                    <h4>Описание фильма:</h4>
                    <p>{{ film.description }}</p>
                    <h4>Дата выхода:</h4>
                    <p>{{ film.date_publ }}</p>
                    <h4>Режиссеры:</h4>
                    {% for direct in film.directions.all %}
                        {{ direct.name }}
                    {% endfor %}
                    <h4>Жанры:</h4>
                    {% for genr in film.genre.all %}
                        {{ genr.name }}
                    {% endfor %}
                </div>
            </div>
                <div class="image"><img src="{{ film.image.url }}" data-rjs="2"></div>
        </div>
    </section>
    <div>
        <span>Оставить отзыв</span>
        <form action="{% url 'add_review' film.id %}" method="post">
            {% csrf_token %}
            <div>
                <label>Ваш отзыв</label>
                <textarea name="text_reviews"></textarea>
            </div>
                <div>
                    <label>Ваше имя *</label>
                    <input type="text" name="name">
                </div>
                <div>
                    <label>Ваш Email *</label>
                    <input type="email" name="email">
                </div>
                <div>
                    <input type="submit">
                </div>
        </form>
    </div>
    <div>
        {% for review in film.reviews_set.all %}
        <div>
            <h5>{{ review.name }}</h5>
            <p>{{ review.text_reviews }}</p>
        </div>
        {% endfor %}
    </div>
    <!-- Project End -->


    <!-- Footer Begin -->
    <footer class="footer bg-light section-pattern footer-bg" data-bg-img="assets/img/section-pattern/footer-pattern.png">
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="copyright-text text-center">
                            <span>&copy; Copyright 2022.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

    </footer>
    <!-- Footer End -->


</body>
</html>